# Workflow to create a draft release whenever a tag is pushed to main
# A lot of inspiration/techniques from: https://github.com/courselore/courselore/blob/c0b541d63fc656986ebeab4af3f3dc9bc2909972/.github/workflows/main.yml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build Release

jobs:
  insiders-build:
    strategy:
      matrix:
        os: [windows, ubuntu]
        include:
          - os: windows
            build: |
              npx package
              mv ../Twitter-Follower-Filter.zip ./twitter-follower-filter-${{github.ref_name}}.zip
            artifact: twitter-follower-filter-${{github.ref_name}}.zip
          - os: ubuntu
            build: |
              npx package
              mv ../Twitter-Follower-Filter.tar.gz ./twitter-follower-filter-${{github.ref_name}}.tar.gz
            artifact: twitter-follower-filter-${{github.ref_name}}.tar.gz
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: ${{matrix.build}}
      - uses: actions/upload-artifact@main
        with:
          name: ${{matrix.artifact}}
          path: ${{matrix.artifact}}
  create-draft-release:
    needs: [insiders-build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@main
        with:
          name: twitter-follower-filter-${{github.ref_name}}.zip
      - uses: actions/download-artifact@main
        with:
          name: twitter-follower-filter-${{github.ref_name}}.tar.gz
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref_name}}
          release_name: ${{github.ref_name}}
          draft: true
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create-release.outputs.upload_url}}
          asset_path: twitter-follower-filter-${{github.ref_name}}.zip
          asset_name: twitter-follower-filter-${{github.ref_name}}.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create-release.outputs.upload_url}}
          asset_path: twitter-follower-filter-${{github.ref_name}}.tar.gz
          asset_name: twitter-follower-filter-${{github.ref_name}}.tar.gz
          asset_content_type: application/gzip
